# permissions for end users to edit immiches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: immich-operator
    app.kubernetes.io/managed-by: kustomize
  name: immich-editor-role
rules:
- apiGroups:
  - media.rm3l.org
  resources:
  - immiches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - media.rm3l.org
  resources:
  - immiches/status
  verbs:
  - get
