# This rule is not used by the project immich-operator-v2 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over media.rm3l.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: immich-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: immich-admin-role
rules:
- apiGroups:
  - media.rm3l.org
  resources:
  - immiches
  verbs:
  - '*'
- apiGroups:
  - media.rm3l.org
  resources:
  - immiches/status
  verbs:
  - get
