apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: immich-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Immich is the Schema for the immiches API.
      displayName: Immich
      kind: Immich
      name: immiches.media.rm3l.org
      version: v1alpha1
  description: A Kubernetes Operator for deploying and managing Immich - a high-performance,
    self-hosted photo and video management solution
  displayName: Immich Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - immich
  - photo
  - video
  - self-hosting
  - album
  links:
  - name: Immich Operator
    url: https://github.com/rm3l/immich-operator
  maintainers:
  - email: armel@rm3l.org
    name: Armel Soro
  maturity: alpha
  minKubeVersion: 1.26.0
  provider:
    name: Armel Soro
    url: https://armel.soro.io
  version: 0.0.0
